pool:
  vmImage: "ubuntu-latest"

trigger:
  branches:
    include:
      - 'main'
      - 'release/*'
pr: none

stages:
  - stage: Compile
    jobs:
      - job: Compile
        # pool: vscode-1es-linux
        steps:
          - script: |
              echo HERE
              # sleep 10
              echo HERE2
              echo $(Agent.JobStatus)
              exit 1
  - stage: IM_Notification
    dependsOn:
      - Compile
    # pool: vscode-1es-linux
    jobs:
      - job: IM_Notification
        steps:
          - template: ado-build-chat.yml
