pool:
  vmImage: "ubuntu-latest"

trigger:
  branches:
    include:
      - 'main'
      - 'release/*'
pr: none

parameters:
  - name: VSCODE_PUBLISH
    displayName: "Publish to builds.code.visualstudio.com"
    type: boolean
    default: true
  - name: VSCODE_RELEASE
    displayName: "Release build if successful"
    type: boolean
    default: false

variables:
  - name: VSCODE_PUBLISH
    value: ${{ eq(parameters.VSCODE_PUBLISH, true) }}
  - name: VSCODE_RELEASE
    value: ${{ eq(parameters.VSCODE_RELEASE, true) }}

stages:
  - stage: Compile
    jobs:
      - job: Compile
        steps:
          - script: |
              echo Compile
              exit 1
  # - stage: Windows
  #   dependsOn:
  #     - Compile
  #   jobs:
  #     - job: Windows
  #       steps:
  #         - script: |
  #             echo Windows
  # - stage: LinuxServerDependencies
  #   jobs:
  #     - job: LinuxServerDependencies
  #       steps:
  #         - script: |
  #             echo LinuxServerDependencies
  # - stage: Linux
  #   dependsOn:
  #     - Compile
  #     - LinuxServerDependencies
  #   jobs:
  #     - job: Linux
  #       steps:
  #         - script: |
  #             echo Linux
  # - stage: macOS
  #   dependsOn:
  #     - Compile
  #   jobs:
  #     - job: macOS
  #       steps:
  #         - script: |
  #             echo macOS
  # - ${{ if eq(variables['VSCODE_PUBLISH'], 'true') }}:
  #     - stage: Publish
  #       dependsOn:
  #         - Compile
  #       jobs:
  #         - job: Publish
  #           steps:
  #             - script: |
  #                 echo Publish
  # - ${{ if eq(variables['VSCODE_RELEASE'], 'true') }}:
  #     - stage: Release
  #       dependsOn:
  #         - Publish
  #       jobs:
  #         - job: Release
  #           steps:
  #             - script: |
  #                 echo Release
  - stage: IM_Notification_success
    displayName: IM Notification success
    dependsOn:
      - Compile
      # - Windows
      # - Linux
      # - macOS
      # - Publish
      # - Release
    jobs:
      - job: IM_Notification_success
        variables:
          CURRENT_BUILD_RESULT: succeeded
        steps:
          - template: ado-build-chat.yml
  - stage: IM_Notification_failure
    displayName: IM Notification failure
    dependsOn:
      - Compile
      # - Windows
      # - Linux
      # - macOS
      # - Publish
      # - Release
    condition: failed()
    jobs:
      - job: IM_Notification_failure
        variables:
          CURRENT_BUILD_RESULT: failed
        steps:
          - template: ado-build-chat.yml
