pool:
  vmImage: "ubuntu-latest"

trigger:
  branches:
    include:
      - 'main'
      - 'release/*'
pr: none

stages:
  - stage: Compile
    jobs:
      - job: Compile
        # pool: vscode-1es-linux
        steps:
          - script: |
              echo HERE
              # sleep 10
              echo HERE2
              echo $(Agent.JobStatus)
              exit 1
  - stage: IM_Notification_success
    dependsOn:
      - Compile
    jobs:
      - job: IM_Notification_success
        variables:
          current_build_result: succeeded
        steps:
          - script: |
              echo success
          - template: ado-build-chat.yml
  - stage: IM_Notification_failure
    dependsOn:
      - Compile
    condition: failed()
    jobs:
      - job: IM_Notification_failure
        variables:
          current_build_result: failed
        steps:
          - script: |
              echo failure
          - template: ado-build-chat.yml
